### ISSUE TITLE
debugger; present locks functionality

### ISSUE THREAD

**Issue by caiovaccaro** [dmauro/Keypress#104]
There is a call to "debugger" in the production file, which causes the script to stop executing.

https://github.com/dmauro/Keypress/blob/master/keypress.js#L398

**Comment by dmauro** [comment]
I've fixed this in develop, but it seemed like this probably didn't warrant it's own release. If really is a big pita I can push a new release. Anyone feel free to chime in, thanks!

**Comment by dmauro** [comment]
https://github.com/dmauro/Keypress/commit/0c01fc284ccd081efc7e0d08cc8fdc3474f5d4ab
