### ISSUE TITLE
ctrl + s and input fields

### ISSUE THREAD

**Issue by gbaumgart** [dmauro/Keypress#108]
I'd like to register a combo on the parent container of a text-area ('ctrl s' to trigger a custom save action) . I tried all possible settings but: 

- it opens file save dialog (which i don't want) or
- it doesn't let me type 's' in a text area

what settings i have to use in this case ? I tried: 

prevent_default : true (doesn't let me type 's' anymore )
prevent_default : false (lets me type 's' but opens the browser file save dialog )

thanks!

**Comment by dmauro** [comment]
From the documentation:
```
prevent_default: Any handlers for your combos will event.preventDefault() for the relevant event by default (you can return true in the handler to prevent this). But there is additionally a prevent_default property which will preventDefault() for events of keypresses of all constituent keys of the combo. What this means is that if you have a combo "shift s", both 'shift' and 's' keypresses will independently preventDefault() when pressed.
```
By default your handler should prevent the default behavior, you don't want to use the prevent_default option because that's more for each constituent keypress that went into the combo. Could you post your code snippet?

**Comment by gbaumgart** [comment]
ups, thats right, ash on my head. thanks again!

**Comment by dmauro** [comment]
This isn't the first time I've seen this though. I think I should rename that property `prevent_all_defaults` which will perhaps be more clear.

**Comment by gbaumgart** [comment]
you have a jsfiddle for your lib?

**Comment by dmauro** [comment]
Hmmm, I do not, but that's not a bad idea...
