### ISSUE TITLE
Caps Lock remains in the `_keys_down` array.

### ISSUE THREAD

**Issue by beaudesigns** [dmauro/Keypress#114]
I've only tested on a Mac, however, the `caps` indicator remains in the `_keys_down` array when turned on. This results in `is_solitary` key combinations not being able to be triggered since `caps` is down.

This happens at the OS level, as you can see by triggering Caps Lock on this page: http://www.asquare.net/javascript/tests/KeyCode.html – There is a `keyDown` event, but no `keyUp` event until the key is pressed again.

**Comment by dmauro** [comment]
This seems to be working as expected because it's a toggle button. If you want to do any logic using a lock key, you'll have to get more explicit in the key bindings using down and up events.

**Comment by beaudesigns** [comment]
Sorry, I think I'm missing something. The primary issue is with `is_solitary: true` hotkeys. Since it still sees "caps" as down.

When you say that I'd have to get more explicit to avoid this, what do you mean?

**Comment by dmauro** [comment]
Do you have a code example of what you're trying to do?

**Comment by beaudesigns** [comment]
Sure thing. 

Gist: https://gist.github.com/beaudesigns/1ba1750003b36134f680f1fd39a231b1
Do it Live: http://bl.ocks.org/beaudesigns/1ba1750003b36134f680f1fd39a231b1

**Comment by dmauro** [comment]
Okay, a couple thoughts:
* We could special case any locking keys to be ignored by is_solitary
* Perhaps there is some way to check on the caps state and add it to the pressed list if it's on when the listener is created to persist through a refresh.
* We could try to "fix" locking keys by immediately firing a key_up after the key_down, and converting the next key_up to both a key_down and key_up. Sounds scary, but would make them behave more like other keys wrt how Keypress treats them.

**Comment by beaudesigns** [comment]
My current work-around is to register a second combo listener for any `is_solitary` hotkeys. I use a registration function for our web app so it makes it easy to do, however, it nearly doubles the amount of listeners in the system. I'm sure that has a performance impact. I implemented this work-around until it can be fixed at the library level.

My initial thought would be to implement another option to Keypress, something like `normalize_toggle_keys` (default to `false`). When `normalize_toggle_keys` is `true`, it would behave like your first option. Ignore locking/toggle keys, and do not add them to the `_keys_down` array.

The only reason I'd hesitate to change the behavior entirely, is to not break any existing code out there that implements the current `caps` behavior. You'd have a better feel for the affects of that though.

-----

By the way, sometimes bug reports can come across as harsh when it's a project you've worked hard on. I just wanted to take a moment to say I _love_ Keypress. It's made the web app I'm working on a breeze. Thanks for all your hard work on it.

**Comment by dmauro** [comment]
Yeah, I think that's a great idea! I'm open to pull requests, but otherwise I'll try to dig into this when I get the chance (might not be soon 😬 ). And thanks for the encouraging words. I'm really glad to hear this project has been helpful for you 😄

**Comment by beaudesigns** [comment]
Pull Request #115
