### ISSUE TITLE
Media keys support

### ISSUE THREAD

**Issue by devkhan** [dmauro/Keypress#122]
Is it possible to capture media keys e.g. play/pause, next, etc.?

I guess they might be platform specific, but does browsers forward these keys' presses to the webpage?

**Comment by beaudesigns** [comment]
Unfortunately media keys do not provide events to the browser. You can test it here: http://www.asquare.net/javascript/tests/KeyCode.html

**Comment by devkhan** [comment]
Nevermind, I've solved my problem with this: https://chrome.google.com/webstore/detail/streamkeys/ekpipjofdicppbepocohdlgenahaneen

I don't know how it does it, but I guess if this can do it, then maybe there is some way to catch media keys inside the browser (or maybe it's just possible in an extension). Maybe.
