### ISSUE TITLE
bug: meta combos are not being unregistered

### ISSUE THREAD

**Issue by bichotll** [dmauro/Keypress#133]
Hi, I came across with an annoying bug. Shortcuts with "meta" can not be unregistered.
At first I thought it was a problem with my script :/

In any case, I've created a demo so you can reproduce it:
http://jsbin.com/xajipev/edit?html,js,console,output
On it you can register/unregister 2 meta/ctrl shortcuts and compare the result/behaviour with the console.

I will review it myself if I have any time...

**Comment by mhuebert** [comment]
I wanted to include Keypress in a little comparison between different keybindings libraries I'm making, but I can't include it because of this bug, it interferes with the other libs when you can't unbind things.

**Comment by mhuebert** [comment]
I have created PR #137 to fix this issue.

**Comment by dmauro** [comment]
Will be fixed in the .5 release
