### ISSUE TITLE
jQuery integration

### ISSUE THREAD

**Issue by MareoRaft** [dmauro/Keypress#134]
I am wondering what the best way is to use your library with a jQuery selector.  I am trying to do something like this:

    $('.input_place').keyComboDown(function(event){
        if( event.keycode == "shift x" ){
            dostuff()
        }
    })

Thanks for your help.

**Comment by dmauro** [comment]
Check out the documentation here: http://dmauro.github.io/Keypress/

You can pass a DOM element into the Listener constructor. You'll need a Listener for each DOM element you want to listen for.
