### ISSUE TITLE
Using with Meteor [ TypeError: Keypress.Listener is not a constructor ]

### ISSUE THREAD

**Issue by lesliechw** [dmauro/Keypress#145]
Meteor latest 1.7 version.
keypress-2.1.5.min.js located at client/lib/keypress-2.1.5.min.js
Tried import in every possible way, include 'require'.

I keep getting the following error:

`TypeError: Keypress.Listener is not a constructor`

I'm pretty sure it's import/include/require issue but can't find out why it doesn't work.

Please advice, thanks.

**Comment by dmauro** [comment]
Here's what it's trying to do re: exporting: https://github.com/dmauro/Keypress/blob/development/keypress.js#L1145-L1153
It could be it's not playing nice with newer ways of doing that. Maybe check if it's defined in `window.keypress` in your environment?

**Comment by lesliechw** [comment]
I put the file to /client/compatibility folder and it's working. But the
"meteor" note you put up, the initialisation step, there is typo error.
Keypress with capital K is wrong. It's small letter k keypress is correct.

Thanks.

**Comment by dmauro** [comment]
Ah, thank you for catching that! I updated that meteor README, so sorry about that. Gonna mark this as closed since it looks like you're all set now.
