### ISSUE TITLE
+/- keys do not register in firefox

### ISSUE THREAD

**Issue by simonsarris** [dmauro/Keypress#50]
The +/- keys on the numpad register, but the +/- keys next to Backspace do not register.

Those two keypresses in Firefox use different e.which values than other browsers, namely 173 for minus and 61 for plus.

Tested on http://dmauro.github.io/Keypress/, it does not work on the sample keyboard.

**Comment by RyanGlScott** [comment]
This doesn't seem to work quite right for me. Testing on this [site](http://dmauro.github.io/Keypress/), pressing `-` on Firefox/Gecko 36 causes the `=` key to be highlighted, and vice versa. Perhaps you mixed up their keycodes in this part of [`keypress.coffee`](http://dmauro.github.io/Keypress/)?

**Comment by jeremykohn** [comment]
Looks like this was corrected on GitHub in version 2.1.1 (May 13).

But not on the website (www.danilatos.com/event-test/ExperimentTest.html), which is still using version 2.1.0.
