### ISSUE TITLE
when registering "meta enter" and "enter" combos with { is_exclusive: true }, the "enter" on_keydown handler never gets called

### ISSUE THREAD

**Issue by thasner** [dmauro/Keypress#60]
verified on Windows 7 chrome, IE11, and firefox

**Comment by roark** [comment]
Hi @dmauro and @thasner,

I'm also experiencing the same issue in Chrome and FF on OS X. The following code fires the `shift tab` callback when `shift tab` is pressed. However, it doesn't fire the `tab` callback at all.

```
keypressListener.register_many([
      {
        "keys"              : "shift tab",
        "is_exclusive"      : true,
        "on_keydown"    : function() {
          console.log("You pressed shift + tab");
        }
      },
      {
        "keys"              : "tab",
        "is_exclusive"      : true,
        "on_keydown"    : function() {
          console.log("You pressed tab");
        }
      }
    ]);
```

If I set either or both `is_exclusive` to `false` then the behavior is that pressing `tab` calls the `tab` callback. Pressing `shift tab` calls both the `tab` and `shift tab` callbacks.

Is this a bug or possibly faulty combo configuration? 

-- Side note: Enjoying the library, keep up the great work.
