### ISSUE TITLE
ctrl+s doesn't work any more

### ISSUE THREAD

**Issue by xwartz** [dmauro/Keypress#64]
```js
{
      "keys": "meta s",
      "is_exclusive": true,
      "is_ordered": true,
      "on_keydown": function(e) {
        // it don't trigger ?
        e.preventDefault();
        return false;
      },
      "on_keyup": function(e) {
       // it's ok
        e.preventDefault();
        return false;
      }
    }
```

when i use ctrl+s under windows ,  "on_keydown" function doesn't run. But it work well under mac.

**Comment by solcik** [comment]
Hello, 

for me "meta s" is working as it should, but has some consequences with me unable to write letters "s" and "S" alone (I am not holding / was not pressing CTRL).

#78

**Comment by dmauro** [comment]
Just tested that and it is working on OS X. I'll take a look into it on Windows, but if that's the case that is definitely unexpected behavior. Thank you for reporting!

**Comment by dmauro** [comment]
What browser is this? I can't reproduce the behavior in Chrome or Firefox in Windows. Could you give a full code sample as well.

**Comment by xwartz** [comment]
Hi, @dmauro  it worked, it's my mistake. Thanks.
