### ISSUE TITLE
Sequence Timing

### ISSUE THREAD

**Issue by ronnyek** [dmauro/Keypress#68]
I've created a sequence that when I hit "` `" (tick tick) I want it to trigger an action.

I can get it to trigger, and it pops up an alert as expected, but then the very next tick I type into say a text field, its popping up the alert again.

My question is, is there any time threshold or setting for that per sequence so that I can say if I typed two ticks in a row, within 500ms, treat it as a sequence, otherwise just let the characters through?

The other thing to note, even though it was triggering the desired action, it was not actually blocking the keypresses in those events (ticks ended up in the textbox)

**Comment by dmauro** [comment]
Just confirmed there is definitely a bug when you try to do a sequence of two of the same characters. Thank you!

**Comment by dmauro** [comment]
https://github.com/dmauro/Keypress/commit/326c417428d00fc5582df520b07f2528b7ad103b
