### ISSUE TITLE
stop_listening() doesn't seem to work as intended

### ISSUE THREAD

**Issue by justinguk** [dmauro/Keypress#69]
When binding stop_listening() to the user being focused on a text field, it should prevent prevent capture, but something doesn't prevent the listener from listening.

**Comment by Canardlaquay** [comment]
It's better to use 
```
$('input').focus(function(){console.log("got focus")}); 
```
now 

Replacement for .bind("blur") is just blur(func)

**Comment by dmauro** [comment]
The problem with your code sample is that you're calling stop_listening as if it were a function instead of a method. The value of `this` in that method is important. Try this:
```$(input).bind("blur", function() { listener.stop_listening; });```
That should do it.

**Comment by dmauro** [comment]
Just realized I made this mistake in my documentation :0
Sorry about that. Fixed: https://github.com/dmauro/Keypress/pull/80
