### ISSUE TITLE
combo collisions

### ISSUE THREAD

**Issue by mc007** [dmauro/Keypress#74]
Hi,
not an issue, I hope and possibly i did something wrong but i really tried almost all combinations of configs/params. 

I have registered 2 simple combos (each is another action):
1. Enter 
2. ctrl enter

When i press, ctrl enter , the listener 1 is fired as well. Do that can work at all like that ?  Or what you would recommend for such case ? 
thank you.

**Comment by FranciscoP** [comment]
Maybe you want the modifier `is_solitary` for the Enter, in this way `Enter` will fire only in 1. and not in 2.

**[See example in jsfiddle](http://jsfiddle.net/franciscop/tbmn7bpy/)**

**Comment by mc007** [comment]
Thank you Francisisco! That worked!
