### ISSUE TITLE
Use cdn.rawgit.com

### ISSUE THREAD

**Issue by qrees** [dmauro/Keypress#76]
replace 
http://rawgit.com/dmauro/Keypress/master/keypress.js
with
http://cdn.rawgit.com/dmauro/Keypress/master/keypress.js
on website

**Comment by sgarza** [comment]
ye cause http://dmauro.github.io/Keypress/ doesn't work

**Comment by leipert** [comment]
I also get the error
Refused to execute script from 'https://rawgithub.com/dmauro/Keypress/master/keypress.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by dmauro** [comment]
Hi, I needed to change the protocol, and I wanted to keep the changes on gh-pages-dev, but thanks for submitting this (I just copy and pasted your link).
