### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by jvc26** [dmauro/Keypress#81]
I can't find much in the documentation or anywhere else as to what browsers receive full support with this library. I note mention of an IE8 shim in the commit logs - is this an IE8+/Chrome/FF/Safari/Opera job, or are earlier IEs supported?

**Comment by dmauro** [comment]
I think earlier IEs might work, but I haven't tested it and I don't have plans to. The library is compatible with all major modern browsers on OS X and Windows (should work in Linux too, but I haven't done any testing there). Hope that answers your question.

**Comment by jvc26** [comment]
Thanks for that much appreciated.
