### ISSUE TITLE
Listener method missing

### ISSUE THREAD

**Issue by ginna-baker** [dmauro/Keypress#86]
I made an input directive that is supposed to stop the library from listening when an input is focused, but it has no effect.  The stop_listening() method that is supposed to be on my listener is not there.  Perhaps deprecated?  What do you suggest?

**Comment by ginna-baker** [comment]
Just solved the problem using the method _prevent_default.  The docs for the library should be updated with this.

**Comment by dmauro** [comment]
The method is there. I'd recommend debugging your code rather than hacking around the issue because other issues will probably pop up.
