### ISSUE TITLE
Suggestion: allow to register listener on multiple elements at the same time

### ISSUE THREAD

**Issue by mallocator** [dmauro/Keypress#89]
Extend the API to support arrays when setting up keylisteners:

Old style:

    new window.keypress.Listener(document.getElementByID('editor'));
    // or with JQuery
    new window.keypress.Listener($('#editor)[0]);

New Style (doesn't really change):

    new window.keypress.Listener(document.getElementByClass('editable'));

This would even make JQuery integration more idiot proof (which I could have used ;-) ):

    new window.keypress.Listener($('#editor));

**Comment by dmauro** [comment]
https://github.com/dmauro/Keypress/commit/1b7da62c0c4b9889df80347a9bd911aeedd57c19
